
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Javier_Andres Herrera Manjarrez
 */
public class ventanaCrudEscuela extends javax.swing.JDialog {

    private Connection conexion;
    private Statement sentencia;
    public ventanaCrudEscuela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PrepararBasedatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDireccion = new javax.swing.JTextArea();
        campoTelefono = new javax.swing.JTextField();
        campoId = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoArea = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoTotalAlumnos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        spidia = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        spiMes = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        spiAnio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos de la escuela", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(65, 66, 68, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(65, 33, 68, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Area de la escuela");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 122, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 300, 68, 26);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 220, 68, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total de alumnos");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 140, 115, 26);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 100, 50, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefono");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 260, 68, 26);

        campoDireccion.setColumns(20);
        campoDireccion.setRows(5);
        campoDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(campoDireccion);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 300, 279, 63);

        campoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(campoTelefono);
        campoTelefono.setBounds(140, 260, 279, 26);

        campoId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdKeyTyped(evt);
            }
        });
        jPanel1.add(campoId);
        campoId.setBounds(141, 34, 279, 26);

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(campoNombre);
        campoNombre.setBounds(141, 66, 279, 30);

        campoArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoAreaKeyTyped(evt);
            }
        });
        jPanel1.add(campoArea);
        campoArea.setBounds(140, 180, 279, 26);

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        campoEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEmailKeyTyped(evt);
            }
        });
        jPanel1.add(campoEmail);
        campoEmail.setBounds(140, 220, 279, 30);

        campoTotalAlumnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTotalAlumnosKeyTyped(evt);
            }
        });
        jPanel1.add(campoTotalAlumnos);
        campoTotalAlumnos.setBounds(140, 140, 279, 26);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Dia: ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 100, 40, 20);

        spidia.setFont(new java.awt.Font("Segoe UI", 0, 14));
        spidia.setEditor(new javax.swing.JSpinner.NumberEditor(spidia, ""));
        jPanel1.add(spidia);
        spidia.setBounds(120, 100, 64, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Mes: ");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(190, 100, 45, 20);

        spiMes.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jPanel1.add(spiMes);
        spiMes.setBounds(230, 100, 64, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Año: ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(300, 100, 45, 20);

        spiAnio.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jPanel1.add(spiAnio);
        spiAnio.setBounds(350, 100, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 90, 433, 374);

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de la escuela");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 22, 433, 35);

        btnAgregar.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(45, 483, 86, 26);

        btnActualizar.setBackground(new java.awt.Color(0, 0, 204));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(381, 483, 97, 26);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 204));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(268, 483, 84, 26);

        btnBuscar.setBackground(new java.awt.Color(0, 0, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(160, 483, 74, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(campoNombre.getText().equals("")
        || campoTotalAlumnos.getText().equals("") || campoArea.getText().equals("") 
        || campoEmail.getText().equals("")|| campoTelefono.getText().equals("")
        || campoDireccion.getText().equals("")){
         JOptionPane.showMessageDialog(null, "1.Digite correctamente cada campo","error",JOptionPane.ERROR_MESSAGE);
         return;
        }
        String fecha =  String.valueOf(spiAnio.getValue())  + "-" + String.valueOf(spiMes.getValue())
                + "-" + String.valueOf(spidia.getValue());
        
        String purueva ="INSERT INTO escuelas "
        + "VALUES(null,'"+campoNombre.getText()+"',"
        + "'"+fecha+"', "+Integer.parseInt(campoTotalAlumnos.getText())+
        ","+ Float.parseFloat(campoArea.getText())+","
        + "'"+campoEmail.getText()+"',"
        + "'"+campoTelefono.getText()+"', '"+campoDireccion.getText()+"');";
        try {
            sentencia.executeQuery(purueva);
            dispose();
        } catch (SQLException ex) {
            if("1062".equals(String.valueOf(ex.getErrorCode()))){
                JOptionPane.showMessageDialog(null,"Correo ya existe no valido\n"
                        + "cambie su correo por otro valido", "error", JOptionPane.WARNING_MESSAGE);
               
            }
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void campoIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
         evt.consume();
        }
        
    }//GEN-LAST:event_campoIdKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        char c = evt.getKeyChar();
        if(campoNombre.getText().length()==200){
        evt.consume();
        }
        if(campoNombre.getText().length() == 0 && c==' '){
         evt.consume();
        }
        if (campoNombre.getText().endsWith(" ") && c == ' ') {// el ultimo caracter es un espacio
            evt.consume();
        }
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoTotalAlumnosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTotalAlumnosKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_campoTotalAlumnosKeyTyped

    private void campoAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAreaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }

        if (campoArea.getText().contains(".") || campoArea.getText().length() == 0) {
            if (c == '.') {
                evt.consume();
            }
        }
        
    }//GEN-LAST:event_campoAreaKeyTyped

    private void campoEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEmailKeyTyped
        char c = evt.getKeyChar();
        if(c==' '){
        evt.consume();
        }
        if(campoEmail.getText().length()==150){
        evt.consume();
        }
    }//GEN-LAST:event_campoEmailKeyTyped

    private void campoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefonoKeyTyped
         char c = evt.getKeyChar();
         if(!Character.isDigit(c)){
         evt.consume();
         }
         if(campoTelefono.getText().length()==15){
         evt.consume();
         }
    }//GEN-LAST:event_campoTelefonoKeyTyped

    private void campoDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDireccionKeyTyped
        char c = evt.getKeyChar();
        if (campoDireccion.getText().endsWith(" ") && c == ' ') {// el ultimo caracter es un espacio
            evt.consume();
           
        }
        if(campoDireccion.getText().length()==0 && c==' '){
        evt.consume();
        }
    }//GEN-LAST:event_campoDireccionKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(campoId.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Primero digiteel ID de la escuela",
                "error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        String sql ="SELECT nombre, fecha, cantidadalumnos, area,"
                + " email, telefono, direccion FROM escuelas\n" +
               "WHERE id="+Integer.parseInt(campoId.getText())+";";
        
        try{
         String d[] = new String[7];
         ResultSet r = sentencia.executeQuery(sql);
         r.next();
         
         
         d[0]= r.getString("nombre");
         d[1]= r.getString("fecha");
         d[2]= r.getString("cantidadalumnos");
         d[3]= r.getString("area");
         d[4]= r.getString("email");
         d[5]= r.getString("telefono");
         d[6]= r.getString("direccion");
         
         campoNombre.setText(d[0]);
        String fecha[] = d[1].split("-");
        SpinnerNumberModel modeloDia = new SpinnerNumberModel();
        modeloDia.setMaximum(31);
        modeloDia.setMinimum(1);
        modeloDia.setValue(Integer.parseInt(fecha[2]));
        spidia.setModel(modeloDia);
        spidia.setEditor(new JSpinner.DefaultEditor(spidia));
        
        SpinnerNumberModel modeloMes = new SpinnerNumberModel();
        modeloMes.setMaximum(12);
        modeloMes.setMinimum(1);
        modeloMes.setValue(Integer.parseInt(fecha[1]));
        spiMes.setModel(modeloMes);
        spiMes.setEditor(new JSpinner.DefaultEditor(spiMes));

        SpinnerNumberModel modeloAnio = new SpinnerNumberModel();
        modeloAnio.setMaximum(3000);
        modeloAnio.setMinimum(1910);
        modeloAnio.setValue(Integer.parseInt(fecha[0]));
        spiAnio.setModel(modeloAnio);
        spiAnio.setEditor(new JSpinner.DefaultEditor(spiAnio));
        
        campoTotalAlumnos.setText(d[2]);
        campoArea.setText(d[3]);
        campoEmail.setText(d[4]);
        campoTelefono.setText(d[5]);
        campoDireccion.setText(d[6]);
        
        
        }catch(SQLException ex){
        
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(campoNombre.getText().equals("")|| campoId.getText().equals("")
        || campoTotalAlumnos.getText().equals("") || campoArea.getText().equals("") 
        || campoEmail.getText().equals("")|| campoTelefono.getText().equals("")
        || campoDireccion.getText().equals("")){
         JOptionPane.showMessageDialog(null, "1. Busque por el ID "
                 + "la institución a  borrar","error",JOptionPane.ERROR_MESSAGE);
         return;
        }
        
        int confir = JOptionPane.showConfirmDialog(null, "Seguro de borrar la "
                + "institución con el id = "+campoId.getText()+"", "confirme",
                JOptionPane.YES_NO_OPTION, JOptionPane.DEFAULT_OPTION);
        if (confir == JOptionPane.YES_OPTION) {
            try {
                sentencia.executeQuery("DELETE FROM escuelas WHERE id="+
                        Integer.parseInt(campoId.getText())+";");
                JOptionPane.showMessageDialog(null, "Se a borrado exitosamente",
                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (SQLException ex) {
                
            }
        }else{
        return;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(campoNombre.getText().equals("")|| campoId.getText().equals("")
        || campoTotalAlumnos.getText().equals("") || campoArea.getText().equals("") 
        || campoEmail.getText().equals("")|| campoTelefono.getText().equals("")
        || campoDireccion.getText().equals("")){
         JOptionPane.showMessageDialog(null, "1. Busque por el ID "
                 + "la institución a editar","error",JOptionPane.ERROR_MESSAGE);
         return;
        }
        
        int confir = JOptionPane.showConfirmDialog(null, "Seguro de actualizar los "
                + "datos de la institución con el id = "+campoId.getText()+"", "confirme",
                JOptionPane.YES_NO_OPTION, JOptionPane.DEFAULT_OPTION);
        if (confir == JOptionPane.YES_OPTION) {
            try {
                String fecha =  String.valueOf(spiAnio.getValue())  + "-" + String.valueOf(spiMes.getValue())
                + "-" + String.valueOf(spidia.getValue());
                
                String sql="UPDATE escuelas SET nombre='"+campoNombre.getText()+"',"
                        + " fecha='"+fecha+"',"
                        + " cantidadalumnos="+Integer.parseInt(campoTotalAlumnos.getText())+","
                        + " area="+Float.parseFloat(campoArea.getText())+","
                        + " email='"+campoEmail.getText()+"',"
                        + " telefono='"+campoTelefono.getText()+"',"
                        + " direccion='"+campoDireccion.getText()+"'"
                        + " WHERE id="+Integer.parseInt(campoId.getText())+";";
                sentencia.executeQuery(sql);
                JOptionPane.showMessageDialog(null, "Se actualizaron los datos exitosamente",
                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (SQLException ex) {
                
            }
        }else{
        return;
        }
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed
    private void PrepararBasedatos() {
        try {
            String DSN = "jdbc:mariadb://localhost:3306/escuela?";
            String user = "user=root&";
            String password = "password=root";
            conexion = DriverManager.getConnection(DSN + user + password);
           // JOptionPane.showMessageDialog(null, "Conexion exitosa");
        } catch (SQLException ded) {
            JOptionPane.showMessageDialog(null, "Error al realizar la conexión", "error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            sentencia = conexion.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al realizar sentencia en la BD", "error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCrudEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCrudEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCrudEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCrudEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaCrudEscuela dialog = new ventanaCrudEscuela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void activos(boolean b1,boolean b2,boolean b3,boolean b4, boolean campoID){
        btnAgregar.setEnabled(b1);
        btnBuscar.setEnabled(b2);
        btnEliminar.setEnabled(b3);
        btnActualizar.setEnabled(b4);
        this.campoId.setEditable(campoID);
        
        
        String fecha[];
        Date daano = new Date();
        SimpleDateFormat fe = new SimpleDateFormat("dd-MM-YYYY");
        String auxi = String.valueOf(fe.format(daano));
        fecha = auxi.split("-");
        
        SpinnerNumberModel modeloDia = new SpinnerNumberModel();
        modeloDia.setMaximum(31);
        modeloDia.setMinimum(1);
        modeloDia.setValue(Integer.parseInt(fecha[0]));
        spidia.setModel(modeloDia);
        spidia.setEditor(new JSpinner.DefaultEditor(spidia));
        
        SpinnerNumberModel modeloMes = new SpinnerNumberModel();
        modeloMes.setMaximum(12);
        modeloMes.setMinimum(1);
        modeloMes.setValue(Integer.parseInt(fecha[1]));
        spiMes.setModel(modeloMes);
        spiMes.setEditor(new JSpinner.DefaultEditor(spiMes));

        SpinnerNumberModel modeloAnio = new SpinnerNumberModel();
        modeloAnio.setMaximum(3000);
        modeloAnio.setMinimum(1910);
        modeloAnio.setValue(Integer.parseInt(fecha[2]));
        spiAnio.setModel(modeloAnio);
        spiAnio.setEditor(new JSpinner.DefaultEditor(spiAnio));
        
        
        
    }
    public void vaciarCampos(){
        campoId.setText("");campoNombre.setText("");campoTotalAlumnos.setText("");
        campoEmail.setText("");campoArea.setText("");campoDireccion.setText("");
        campoTelefono.setText("");
    }
    
    public String manejarFecha(){
     String f ="";
     
     
     
        
     
     return f;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTextField campoArea;
    private javax.swing.JTextArea campoDireccion;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoTotalAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spiAnio;
    private javax.swing.JSpinner spiMes;
    private javax.swing.JSpinner spidia;
    // End of variables declaration//GEN-END:variables
}
